name: circle_checkbox
description: Make Material CheckBox Circle
version: 0.0.2+1
homepage: https://www.facebook.com/REDEVRX
repository: https://github.com/redevRx/CircleCheckBox
author: Kasem Saikhuedong<redev.rx@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
