name: circle_check
description: Make Material CheckBox Circle
version: 0.0.1+1
homepage: https://www.facebook.com/REDEVRX
repository: https://github.com/badeesAbood/CircleCheckBox.git
author: badeesAbood

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
